# Generated by Django 5.2.3 on 2025-06-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
