# Generated by Django 5.2.3 on 2025-06-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_create_by_item_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
    ]
